import { ChevronRight, Calendar, Shield, Check, Play } from 'lucide-react';
import Link from 'next/link';


/* ==========================================
   AD PANEL (Desktop side panels)
   ========================================== */

const AD_EMAIL_SUBJECT = encodeURIComponent('Advertising Inquiry - Bracket Blocker');
const AD_EMAIL_BODY = encodeURIComponent(`Hi Bracket Blocker team,

I'm interested in advertising on Bracket Blocker during the 2026 NCAA Tournament.

=== PREMIUM SPONSORSHIP OPPORTUNITY ===
Your brand can appear in EVERY calendar invite generated by our users!

Example: "Bracket Blocker is sponsored by [Your Brand]. Sign up at [YourSite.com/promo]"

This message appears in the calendar description of every fake meeting our users create - putting your brand directly on their work calendars throughout March.

=== YOUR INFO ===
Company/Brand: [Your company name]
Website: [Your website URL]
Budget range: [Your budget]
Campaign dates: [When you'd like to run]

Additional details:
[Tell us about your campaign goals]

Looking forward to hearing from you!

Best,
[Your name]`);

const AD_MAILTO = `mailto:hello@bracketblocker.com?subject=${AD_EMAIL_SUBJECT}&body=${AD_EMAIL_BODY}`;


function AdPanel({ side }: { side: 'left' | 'right' }) {
  return (
    <div className={`hidden xl:block ad-panel-wrapper ${side === 'left' ? 'mr-4 xl:mr-6' : 'ml-4 xl:ml-6'}`}>
      <div className={`ad-panel ${side === 'left' ? 'ad-panel-left' : 'ad-panel-right'} p-2 w-32 xl:w-36 2xl:w-44`}>
        <div className="ad-panel-screen h-[360px] xl:h-[420px] 2xl:h-[480px] flex flex-col items-center justify-center text-center p-4 relative scanlines">
          <span className="text-[9px] uppercase tracking-widest text-zinc-600 mb-4">Sponsored</span>
          <span className="text-lg xl:text-xl text-zinc-400 font-[var(--font-oswald)] uppercase mb-1">Your Ad</span>
          <span className="text-xl xl:text-2xl text-[var(--led-amber)] led-text font-[var(--font-oswald)] font-bold uppercase mb-6">Here</span>
          <p className="text-[9px] text-zinc-600 mb-4 leading-relaxed">Reach 100k+ basketball fans</p>
          <a href={AD_MAILTO} className="text-[9px] uppercase tracking-widest text-[var(--led-amber)] opacity-70 hover:opacity-100 transition-opacity">
            Advertise →
          </a>
        </div>
      </div>
    </div>
  );
}

/* ==========================================
   AD BANNER (Mobile/Tablet horizontal)
   ========================================== */

function AdBanner() {
  return (
    <div className="xl:hidden w-full max-w-3xl mx-auto px-4 mb-6">
      <div className="ad-banner bg-black/80 border-2 border-[var(--led-amber)]/30 rounded-lg p-4 flex items-center justify-between shadow-[0_0_20px_rgba(255,150,0,0.15)]">
        <div className="flex items-center gap-4">
          <span className="text-[9px] uppercase tracking-widest text-zinc-500">Sponsored</span>
          <div className="flex items-center gap-2">
            <span className="text-sm text-zinc-300 font-[var(--font-oswald)] uppercase">Your Ad</span>
            <span className="text-sm text-[var(--led-amber)] led-text font-[var(--font-oswald)] font-bold uppercase">Here</span>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <p className="text-[9px] text-zinc-500 hidden sm:block">Reach 100k+ fans</p>
          <a href={AD_MAILTO} className="text-[9px] uppercase tracking-widest text-[var(--led-amber)] hover:text-[var(--led-amber-glow)] transition-colors whitespace-nowrap">
            Advertise →
          </a>
        </div>
      </div>
    </div>
  );
}

/* ==========================================
   MAIN PAGE
   ========================================== */

export default function Home() {
  return (
    <>
      {/* Background */}
      <div className="arena-bg"></div>
      <div className="arena-vignette"></div>

      <main className="relative z-10 min-h-screen">

        {/* ===== HERO SECTION ===== */}
        <section className="min-h-screen flex flex-col items-center justify-center px-4 py-16">

          {/* Mobile/Tablet Ad Banner - shows when side panels are hidden */}
          <AdBanner />

          <div className="flex items-center justify-center w-full max-w-[1600px]">

            <AdPanel side="left" />

            {/* Jumbotron */}
            <div className="w-full max-w-3xl xl:max-w-4xl jumbotron-wrapper">
              <div className="jumbotron-3d animate-float">
                {/* Hanging cables */}
                <div className="hidden md:flex justify-center gap-32 xl:gap-40 mb-0">
                  <div className="w-1 h-16 xl:h-20 bg-gradient-to-b from-zinc-600 to-zinc-800 rounded-full shadow-lg"></div>
                  <div className="w-1 h-16 xl:h-20 bg-gradient-to-b from-zinc-600 to-zinc-800 rounded-full shadow-lg"></div>
                </div>

                <div className="jumbotron-outer">
                  <div className="jumbotron-bezel">
                    <div className="jumbotron-screen scanlines dot-matrix screen-glow px-6 py-8 md:px-10 md:py-12 xl:px-12 xl:py-14">

                      {/* Live badge */}
                      <div className="flex justify-center mb-8">
                        <div className="flex items-center gap-2 px-4 py-1.5 rounded-full bg-black/50 border border-green-500/30">
                          <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse-glow"></span>
                          <span className="text-[10px] md:text-xs uppercase tracking-widest text-green-400 font-bold font-[var(--font-oswald)]">
                            Bracket Live • NCAA Tournament 2026
                          </span>
                        </div>
                      </div>

                      {/* Title */}
                      <h1 className="text-center mb-6">
                        <span className="block text-5xl sm:text-6xl md:text-7xl lg:text-8xl font-black uppercase tracking-tighter text-[var(--led-amber)] led-text animate-flicker font-[var(--font-oswald)]">
                          Bracket
                        </span>
                        <span className="block text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold uppercase tracking-wide text-[var(--led-white)] led-text-white font-[var(--font-oswald)] -mt-1 md:-mt-2">
                          Blocker
                        </span>
                      </h1>

                      {/* Tagline */}
                      <p className="text-center text-sm md:text-base text-zinc-300 mb-10 max-w-lg mx-auto font-[var(--font-inter)]">
                        Generate fake work calendar invites for NCAA Tournament games.
                        <span className="block text-zinc-500 text-xs md:text-sm mt-1 uppercase tracking-wider">
                          Your boss will never know.
                        </span>
                      </p>

                      {/* CTA */}
                      <div className="flex flex-col items-center relative z-[100]">
                        <Link
                          href="/bracket"
                          className="btn-glow px-8 md:px-12 py-4 flex items-center gap-2 cursor-pointer relative z-[100] text-lg md:text-xl font-bold uppercase tracking-wider text-[var(--led-amber)] led-text font-[var(--font-oswald)] no-underline"
                        >
                          <Calendar className="w-5 h-5" />
                          View Bracket & Block Calendar
                          <ChevronRight className="w-5 h-5" />
                        </Link>
                        <span className="text-[10px] md:text-xs text-zinc-600 mt-3 uppercase tracking-widest">
                          Tournament starts March 19
                        </span>
                      </div>

                    </div>
                  </div>
                </div>

                {/* Bottom vents */}
                <div className="flex justify-center gap-1 mt-3 opacity-40">
                  {[...Array(18)].map((_, i) => (
                    <div key={i} className="w-1 h-3 md:h-5 bg-black rounded-full"></div>
                  ))}
                </div>
              </div>
            </div>

            <AdPanel side="right" />

          </div>

          {/* Bottom Mobile/Tablet Ad Banner */}
          <AdBanner />

        </section>

        {/* ===== BRACKET IS LIVE ===== */}
        <section id="bracket-live" className="py-16 px-4 bg-gradient-to-b from-[var(--arena-black)] to-[var(--arena-dark)] border-t border-b border-green-500/20">
          <div className="max-w-3xl mx-auto text-center">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-green-500/10 border border-green-500/30 mb-6">
              <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></span>
              <span className="text-sm text-green-400 font-bold uppercase tracking-wider">
                Bracket is Live
              </span>
            </div>

            <h2 className="text-3xl md:text-4xl font-bold mb-4 font-[var(--font-oswald)] uppercase">
              <span className="text-white">The Tournament </span>
              <span className="text-[var(--led-amber)]">Starts Now</span>
            </h2>

            <p className="text-zinc-400 mb-8 max-w-xl mx-auto">
              64 teams. Your boss doesn't need to know you're watching.
              Block your calendar with fake meetings and enjoy the madness.
            </p>

            <Link
              href="/bracket"
              className="inline-flex items-center gap-2 px-8 py-4 bg-[var(--led-amber)] hover:bg-[var(--led-amber-glow)] text-black font-bold rounded-lg transition-all uppercase tracking-wider shadow-lg hover:shadow-[0_0_30px_rgba(255,150,0,0.4)]"
            >
              <Calendar className="w-5 h-5" />
              View Bracket & Block Calendar
              <ChevronRight className="w-5 h-5" />
            </Link>
          </div>
        </section>

        {/* ===== HOW IT WORKS ===== */}
        <section className="py-24 px-4 bg-[var(--arena-dark)] border-t border-white/5">
          <div className="max-w-5xl mx-auto">
            <h2 className="text-center text-3xl md:text-4xl font-bold mb-4 uppercase tracking-tight font-[var(--font-oswald)]">
              <span className="text-white">How It </span>
              <span className="text-[var(--led-amber)]">Works</span>
            </h2>
            <p className="text-center text-zinc-500 mb-16 text-sm">
              Three steps to basketball freedom during work hours.
            </p>

            <div className="grid md:grid-cols-3 gap-6 md:gap-8">
              {[
                { num: '01', icon: Shield, title: 'Pick Your Games', desc: 'Select your favorite teams, conferences, or specific matchups you refuse to miss.' },
                { num: '02', icon: Calendar, title: 'Choose Your Cover', desc: 'Pick from boring meeting templates like "Q1 Synergy Sync" or write your own.' },
                { num: '03', icon: Check, title: 'Block Your Calendar', desc: 'Get calendar invites that sync directly to Google Calendar or Outlook.' },
              ].map((item) => (
                <div key={item.num} className="feature-card p-8 relative group">
                  <div className="absolute -top-4 left-6 w-10 h-10 rounded-lg bg-[var(--arena-black)] border border-white/10 flex items-center justify-center">
                    <span className="text-[var(--led-amber)] font-bold font-[var(--font-oswald)]">{item.num}</span>
                  </div>
                  <item.icon className="w-8 h-8 text-zinc-500 mb-6 mt-2 group-hover:text-[var(--led-amber)] transition-colors" />
                  <h3 className="text-xl font-bold uppercase tracking-wide mb-3 font-[var(--font-oswald)] text-white">
                    {item.title}
                  </h3>
                  <p className="text-zinc-400 text-sm leading-relaxed font-[var(--font-inter)]">
                    {item.desc}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ===== PREVIEW SECTION ===== */}
        <section className="py-24 px-4">
          <div className="max-w-5xl mx-auto grid md:grid-cols-2 gap-12 md:gap-16 items-center">
            <div>
              <h2 className="text-3xl md:text-4xl font-bold mb-6 uppercase tracking-tight font-[var(--font-oswald)]">
                <span className="text-white">The </span>
                <span className="text-[var(--led-amber)]">Perfect Crime</span>
              </h2>
              <p className="text-zinc-400 mb-8 leading-relaxed font-[var(--font-inter)]">
                Your calendar says "Enterprise Architecture Review." Your screen says UNC vs Duke.
                We provide the legitimate-looking cover stories so you can enjoy the madness.
              </p>
              <ul className="space-y-4">
                {['Authentic corporate jargon', 'Realistic duration times', 'Automatic follow-ups when your team wins'].map((item, i) => (
                  <li key={i} className="flex items-center gap-3 text-zinc-300 font-[var(--font-inter)]">
                    <Play className="w-4 h-4 text-[var(--led-amber)] fill-[var(--led-amber)]" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>

            {/* Calendar mockup */}
            <div className="relative">
              <div className="absolute inset-0 bg-[var(--led-amber)]/20 blur-[80px] rounded-full"></div>
              <div className="calendar-preview p-6 relative rotate-1 hover:rotate-0 transition-transform duration-500">
                <div className="flex items-center justify-between mb-6 pb-4 border-b border-gray-200">
                  <span className="font-bold text-lg text-gray-900">Calendar</span>
                  <span className="text-gray-400 text-sm">March 19, 2026</span>
                </div>
                <div className="space-y-3">
                  <div className="flex gap-4 opacity-40">
                    <span className="text-xs text-gray-400 font-mono w-14 text-right pt-3">1:00 PM</span>
                    <div className="flex-1 bg-gray-100 p-3 rounded-lg">
                      <div className="h-2 w-24 bg-gray-300 rounded mb-2"></div>
                      <div className="h-2 w-32 bg-gray-200 rounded"></div>
                    </div>
                  </div>
                  <div className="flex gap-4 relative">
                    <span className="text-xs text-gray-400 font-mono w-14 text-right pt-3">2:00 PM</span>
                    <div className="flex-1 bg-blue-50 border-l-4 border-blue-500 p-4 rounded-r-lg shadow-md">
                      <div className="font-semibold text-blue-900">Q1 Roadmap Alignment</div>
                      <div className="text-xs text-blue-600 mt-1">Conference Room B • Mandatory</div>
                    </div>
                    <div className="absolute -right-3 -top-3 bg-[var(--led-amber)] text-black font-bold text-xs px-3 py-1.5 rounded-lg shadow-lg rotate-6 animate-pulse">
                      Actually: Duke vs UNC
                    </div>
                  </div>
                  <div className="flex gap-4 opacity-40">
                    <span className="text-xs text-gray-400 font-mono w-14 text-right pt-3">5:00 PM</span>
                    <div className="flex-1 bg-gray-100 p-3 rounded-lg">
                      <div className="h-2 w-20 bg-gray-300 rounded"></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ===== FINAL CTA ===== */}
        <section className="py-20 px-4 bg-[var(--arena-frame)] border-t border-black/50 relative">
          <div className="absolute inset-0 bg-scanlines opacity-5 pointer-events-none"></div>
          <div className="max-w-2xl mx-auto text-center relative z-10">
            <h2 className="text-3xl md:text-5xl font-bold mb-4 uppercase font-[var(--font-oswald)]">
              <span className="text-white led-text-white">Block Your </span>
              <span className="text-[var(--led-amber)] led-text">Calendar Now</span>
            </h2>
            <p className="text-zinc-400 mb-8 max-w-md mx-auto">
              The bracket is live. Pick your games and generate fake meetings before your boss schedules something.
            </p>
            <Link
              href="/bracket"
              className="inline-flex items-center gap-2 bg-[var(--led-amber)] hover:bg-[var(--led-amber-glow)] text-black font-bold text-lg md:text-xl px-10 py-4 rounded-lg uppercase tracking-wider font-[var(--font-oswald)] transition-all shadow-lg hover:shadow-[0_0_30px_rgba(255,150,0,0.5)] cursor-pointer"
            >
              <Calendar className="w-5 h-5" />
              View Bracket
              <ChevronRight className="w-5 h-5" />
            </Link>
            <p className="mt-8 text-zinc-500 text-sm">
              © 2026 Bracket Blocker. Not affiliated with the NCAA.
            </p>
          </div>
        </section>

      </main>
    </>
  );
}
